package easy;

/**
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 *
 * Example:
 * Input:
 * s = "abcd"
 * t = "abcde"
 * Output:
 * e
 * Explanation:
 * 'e' is the letter that was added.
 *
 * 解决思路:
 * 拆分为两个char数组并循环对比，将s里有t里也有的字母置为0，剩下的一个为额外添加的
 *
 * Created by second on 2017/7/18.
 */
public class FindTheDifference {

    public char findTheDifference(String s, String t) {
        char[] a = new char[s.length()];
        s.getChars(0, s.length(), a, 0);
        char[] b = new char[t.length()];
        t.getChars(0, t.length(), b, 0);
        for (int i = 0; i < a.length; i++)
            for (int j = 0; j < b.length; j++)
                if (a[i] == b[j]){
                    b[j] = 0;
                    break;
                }
        for (char c: b)
            if (c != 0)
                return c;
        return 0;
    }

}
